#Resource locations of disallowed actions. Trying to cast one of these will result in a mishap.
actionDenyList = []

[Spells]
	#How many times a spell can recursively cast other spells
	#Range: > 0
	maxRecurseDepth = 64
	#The harvest level of the Break Block spell.
	#0 = wood, 1 = stone, 2 = iron, 3 = diamond, 4 = netherite.
	#Range: 0 ~ 4
	opBreakHarvestLevel = 3

["Spell Circles"]
	#The maximum number of slates in a spell circle
	#Range: > 4
	maxSpellCircleLength = 256

